package com.payslipmax.pdfparser.ui.screens

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import com.payslipmax.pdfparser.insights.InsightSeverity
import com.payslipmax.pdfparser.insights.TaxBlufSummary
import com.payslipmax.pdfparser.ui.theme.AppDimensions
import com.payslipmax.pdfparser.ui.theme.severityColor

/**
 * Phase 8 (U3): "Bottom Line Up Front" -- the one plain-language sentence a reader with no tax
 * background needs before the detailed cards below, plus a single no-action/flag line so they don't
 * have to synthesize that verdict themselves out of several cards' worth of numbers. Every word here
 * is generated by [com.payslipmax.pdfparser.insights.ConversationalTaxNarrativeEngine.buildBluf] --
 * this composable only renders it.
 */
@Composable
fun TaxBlufSummaryCard(
    bluf: TaxBlufSummary,
    modifier: Modifier = Modifier,
) {
    val severity = if (bluf.isActionRequired) InsightSeverity.WARNING else InsightSeverity.INFO
    FlatBorderedCard(tint = CardTint.Accent, modifier = modifier, contentSpacing = AppDimensions.SpacingSmall) {
        Text(
            text = bluf.headline,
            style = MaterialTheme.typography.bodyLarge,
            color = MaterialTheme.colorScheme.onSurface,
        )
        Text(
            text = bluf.actionLine,
            style = MaterialTheme.typography.bodyMedium,
            fontWeight = FontWeight.SemiBold,
            color = severityColor(severity),
        )
    }
}
