package com.payslipmax.pdfparser.di

import com.payslipmax.pdfparser.guide.GuideBundleSource
import com.payslipmax.pdfparser.guide.GuideRepository
import com.payslipmax.pdfparser.guide.data.GuideNotesRepository
import com.payslipmax.pdfparser.guide.data.GuidePinsStorage
import com.payslipmax.pdfparser.guide.data.LazyGuideRepository
import com.payslipmax.pdfparser.guide.data.PayslipGuideProfileProvider
import com.payslipmax.pdfparser.guide.data.RoomGuideNotesRepository
import com.payslipmax.pdfparser.guide.data.provideGuidePinsStorage
import com.payslipmax.pdfparser.guide.domain.GuideProfileProvider
import com.payslipmax.pdfparser.repository.PayslipRepository
import com.payslipmax.pdfparser.ui.screens.guide.GuideNotesViewModel
import com.payslipmax.pdfparser.ui.screens.guide.GuidePinsModel
import com.payslipmax.pdfparser.ui.screens.guide.GuideSearchViewModel
import com.payslipmax.pdfparser.ui.screens.guide.GuideViewModel
import kotlinx.coroutines.Dispatchers
import org.koin.dsl.module
import pdfparser.composeapp.generated.resources.Res

/** Generated by `docs/Plan/rule_cards/tools/bundle.py`; a compose resource so both platforms read the same file. */
internal const val GUIDE_BUNDLE_PATH = "files/guide/guide_bundle.json"

/**
 * Claim Guide bindings. Lives in composeApp because the bundle is a compose resource ([Res] is generated
 * here); everything else is in `shared`. Nothing is read until a Guide screen first asks the repository.
 */
val guideModule =
    module {
        single<GuideBundleSource> { GuideBundleSource { Res.readBytes(GUIDE_BUNDLE_PATH).decodeToString() } }
        // One repository per process, so the bundle is parsed once however many Guide screens ask.
        single<GuideRepository> { LazyGuideRepository(source = get(), dispatcher = Dispatchers.Default) }
        // App-scoped: switching tabs or locking the app keeps the loaded Guide; it holds no screen state.
        // The profile is read from the stored payslips on device, only while an unlocked figure card is open.
        single<GuideProfileProvider> { PayslipGuideProfileProvider { get<PayslipRepository>().getAllPayslips() } }
        // Pins are plain card ids on the device (SharedPreferences / NSUserDefaults), not in the Room database or the backup.
        single<GuidePinsStorage> { provideGuidePinsStorage() }
        single { GuidePinsModel(storage = get()) }
        // Personal notes: encrypted rows in the same Room database as payslips (so the .pcda backup carries them), unlike pins.
        single<GuideNotesRepository> { RoomGuideNotesRepository(dao = get()) }
        single { GuideViewModel(repository = get(), crashReporter = get(), profiles = get(), pins = get()) }
        // App-scoped like the Guide model; reads the notes only while a screen collects them, and has no crash reporter.
        single { GuideNotesViewModel(repository = get(), guide = get()) }
        // App-scoped so a query and its results survive opening a card; memory only, never saved or sent. Searches the notes too.
        single { GuideSearchViewModel(guide = get(), notes = get()) }
    }
