package com.payslipmax.pdfparser.di

import com.payslipmax.pdfparser.guide.GuideBundleSource
import com.payslipmax.pdfparser.guide.GuideRepository
import com.payslipmax.pdfparser.guide.data.LazyGuideRepository
import com.payslipmax.pdfparser.ui.screens.guide.GuideViewModel
import kotlinx.coroutines.Dispatchers
import org.koin.dsl.module
import pdfparser.composeapp.generated.resources.Res

/** Generated by `docs/Plan/rule_cards/tools/bundle.py`; a compose resource so both platforms read the same file. */
internal const val GUIDE_BUNDLE_PATH = "files/guide/guide_bundle.json"

/**
 * Claim Guide bindings. Lives in composeApp because the bundle is a compose resource ([Res] is generated
 * here); everything else is in `shared`. Nothing is read until a Guide screen first asks the repository.
 */
val guideModule =
    module {
        single<GuideBundleSource> { GuideBundleSource { Res.readBytes(GUIDE_BUNDLE_PATH).decodeToString() } }
        // One repository per process, so the bundle is parsed once however many Guide screens ask.
        single<GuideRepository> { LazyGuideRepository(source = get(), dispatcher = Dispatchers.Default) }
        // App-scoped: switching tabs or locking the app keeps the loaded Guide; it holds no screen state.
        single { GuideViewModel(repository = get(), crashReporter = get()) }
    }
