package com.payslipmax.pdfparser.ui.theme

object AppStringsPremium {
    const val geminiAiAnalyzeDesc = "Generate professional tax saving suggestions, investment recommendations, and error audits using Gemini."
    const val geminiAiViewReportBtn = "View Full Audit Report"

    // AI CA Audit card (Phase 5)
    const val aiAuditAnalyzingDesc = "Analyzing your payslip with Gemini AI…"
    const val aiAuditSummaryLabel = "Summary"
    const val aiAuditTeaserBullets = "Detect PCDA errors & recoverable amounts\nPersonalised tax-saving strategy (old regime)\nInvestment guidance from your AI CA"
    const val aiAuditUnlockBtn = "Unlock AI CA Audit"
    const val aiAuditPremiumBadge = "Premium"

    // Premium Features Screens Strings
    const val representationTitle = "Official Representations"
    const val representationSubtitle = "Pay & allowance dispute letters"
    const val representationDraftsEmpty = "No salary discrepancies or missing allowances detected. Representation drafts will appear here if the local audit engine flags any issues."
    const val representationCopyBtn = "Copy"
    const val representationEditBtn = "Edit"
    const val representationSaveBtn = "Save Draft"
    const val representationShareBtn = "Share"
    const val representationExportPdfBtn = "Export PDF"

    // Retirement calculators (RETIREMENT_CALCULATORS gate, Phase 4e). All outputs are estimates.
    const val retCalcTitle = "Retirement Calculators"
    const val retCalcSubtitle = "Pension, gratuity, commutation & leave estimates"
    const val retCalcNoPayslip = "Select a payslip first — these estimates use your current pay figures."
    const val retCalcBasisLabel = "Based on current pay (Basic + MSP + DA)"
    const val retCalcInputsTitle = "Your details"
    const val retCalcQualifyingYearsLabel = "Qualifying service (years)"
    const val retCalcAgeNextBirthdayLabel = "Age next birthday at retirement (55–65)"
    const val retCalcLeaveDaysLabel = "Encashable leave days (max 300)"
    const val retCalcPensionTitle = "Estimated monthly pension"
    const val retCalcPensionNote = "50% of Basic + MSP"
    const val retCalcGratuityTitle = "Estimated retirement gratuity"
    const val retCalcGratuityNote = "¼ × (Basic + DA) × six-monthly periods, capped"
    const val retCalcCommutationTitle = "Commuted lump sum (50%)"
    const val retCalcCommutationResidualPrefix = "Residual monthly pension: "
    const val retCalcCommutationNoFactor = "Enter an age between 55 and 65 to estimate commutation, or verify your factor with PAO."
    const val retCalcLeaveTitle = "Estimated leave encashment"
    const val retCalcLeaveNote = "(Basic + DA) ÷ 30 × days"
    const val retCalcDisclaimer = "Estimates only, based on your current pay — actual retirement figures depend on last-drawn emoluments and rules in force. Verify with PAO / PCDA(O)."

    const val taxPlanningTitle = "Tax Optimization Planner"
    const val taxPlanningSubtitle = "Form 16 projections & tax-saving suggestions"
    const val taxPlanningGrossYtd = "YTD Gross Salary"
    const val taxPlanningTaxable = "Net Taxable Income"
    const val taxPlanningITax = "Estimated Tax Liability"

    const val retirementTitle = "Retirement Wealth Projection"
    const val retirementSubtitle = "DSOP contribution & compound wealth estimates"
    const val retirementCompounding = "Compounding Growth Projections"
    const val retirementBalance = "Projected DSOP Balance"
    const val retirementContributions = "Total Principal Contributions"
    const val retirementInterest = "Total Interest Earned"
    const val retirementProjectionDisclaimer = "Note: Compounding projections are estimated using a standard interest rate of 7.1% per annum. Actual rates may vary."
    const val premiumToolsTitle = "Premium Financial Tools"
    const val premiumToolsTaxPlanner = "Tax Planner"
    const val premiumToolsDsopSimulator = "DSOP Simulator"

    const val representationMonthLabel = "Month:"
    const val representationRecipientPcda = "Recipient: PCDA Pune"
    const val representationEditDraftTitle = "Edit Draft:"

    const val retirementNoBalance = "Import a payslip with DSOP ledger balance to simulate growth."
    const val retirementCurrentBalance = "Current DSOP Balance"
    const val taxPlanningSavingsProjections = "Section 80C & 80D Tax Savings Projections"
    const val taxPlanningNoProjections = "No YTD Tax Projections available for this month."
    const val taxPlanningCurrentYtdContribution = "Current YTD Contribution: ₹"

    // PRO Features Catalog (Phase 3) — benefit-only copy, no prices (D8)
    const val proCatalogTitle = "PRO Features"
    const val proCatalogSubtitle = "Everything included with PayslipMax Pro"
    const val proCatalogIncludedLabel = "Included"
    const val proCatalogComingSoonLabel = "Coming soon"
    const val proCatalogSettingsEntrySubtitle = "See everything Pro unlocks"

    const val proCatalogPremiumIntelligenceTitle = "Premium Intelligence"
    const val proCatalogPremiumIntelligenceDesc = "Full recovery opportunities, tax savings and CA-level audit in one view"
    const val proCatalogPremiumIntelligenceIcon = "👑"
    const val proCatalogWealthTitle = "Wealth Optimization"
    const val proCatalogWealthDesc = "80C/NPS headroom and DSOP corpus growth projections"
    const val proCatalogWealthIcon = "💰"
    const val proCatalogAiAuditTitle = "AI CA Audit"
    const val proCatalogAiAuditDesc = "On-device AI reviews your payslip for PCDA errors and savings"
    const val proCatalogAiAuditIcon = "🤖"
    const val proCatalogAnomalyTitle = "Advanced Anomaly Detection"
    const val proCatalogAnomalyDesc = "DSOP compliance, arrears, entitlement and recovery-risk audits"
    const val proCatalogAnomalyIcon = "🔍"
    const val proCatalogClaimTitle = "Claim Generator"
    const val proCatalogClaimDesc = "Generate official PCDA(O) representation PDFs"
    const val proCatalogBackupTitle = "Encrypted Backup"
    const val proCatalogBackupDesc = "Create AES-256 encrypted backups of your payslip data"
    const val proCatalogBackupIcon = "🔐"
    const val proCatalogRetCalcTitle = "Retirement Calculators"
    const val proCatalogRetCalcDesc = "Estimate pension, gratuity, commutation & leave encashment"
    const val proCatalogRetCalcIcon = "🧮"
}
