package com.payslipmax.pdfparser.ui.theme

object AppStrings {
    // App Branding & Navigation
    const val appTitle = "PCDA Payslip Portal"
    const val appSubtitle = "Indian Army Personnel Financial Analytics"
    const val navigationHome = "Dashboard"
    const val navigationHistory = "History"
    const val navigationInsights = "Insights"
    const val navigationSettings = "Settings"
    const val badgeOfficer = "Officer"
    const val badgeCda = "CDA A/C No"
    const val badgePan = "PAN"
    const val appVersion = "PayslipMax iOS - Version 1.4.2"

    // Statistics Cards
    const val cardNetTitle = "Latest Net Remittance"
    const val cardNetUnit = "INR (₹)"
    const val cardBpTitle = "Basic Pay (BPAY)"
    const val cardBpUnit = "INR (₹)"
    const val cardBpDesc = "+ Allowances & Arrears"
    const val cardDsopTitle = "DSOP Closing Balance"
    const val cardDsopUnit = "INR (₹)"
    const val cardDsopDesc = "Provident Fund Wealth"
    const val cardTaxTitle = "Effective Tax Rate"
    const val cardTaxUnit = "YTD"
    const val cardTaxDesc = "Average Annual TDS"

    // Dashboard Overview
    const val sectionOverview = "Financial Overview"
    const val sectionCharts = "Analytics Charts"
    const val chartIncomeTitle = "Monthly Payout Trend"
    const val chartShareTitle = "Earnings Allocation"
    const val chartDsopTitle = "DSOP Fund Growth"
    const val chartTaxTitle = "Tax Deductions vs Projections"

    // Explorer
    const val explorerHeader = "Payslip Digital Replica"
    const val explorerSubheader = "Tap any transaction code for detailed explanations"
    const val replicaEarningTitle = "Earnings (₹)"
    const val replicaDeductionTitle = "Deductions (₹)"
    const val replicaGrossLabel = "Gross Pay (कुल आय)"
    const val replicaDeductionsLabel = "Total Deductions (कुल कटौती)"
    const val replicaNetLabel = "Net Remittance (Take Home)"
    const val replicaFooter = "Principal Controller of Defence Accounts (Officers), Pune\nMinistry of Defence, Government of India"
    const val ledgerGrossPay = "Gross Pay (Credits)"
    const val ledgerTotalDeductions = "Total Deductions (Debits)"

    // Replica metadata & glossary
    const val replicaBackDesc = "Back"
    const val replicaOfficerPrefix = "Officer: "
    const val replicaCdaPrefix = "CDA A/C: "
    const val replicaPanPrefix = "PAN: "
    const val glossaryUnderstood = "Understood"

    // Confidence-gated correction (Phase 5)
    const val correctionReviewBadge = "Review"
    const val correctionIndicatorDesc = "Low confidence — tap to review and correct this value"
    const val correctionDialogTitle = "Correct value"
    const val correctionDialogHint = "This value was parsed with low confidence. Enter the correct amount from your payslip."
    const val correctionFieldLabel = "Amount (₹)"
    const val correctionInvalidAmount = "Enter a valid amount"
    const val correctionSave = "Save"
    const val correctionCancel = "Cancel"
    const val correctionAiSourceBadge = "AI"
    const val correctionAiSourceDesc = "This value was inferred by on-device AI (Gemma), not parsed directly — please verify against your payslip"
    const val correctionReasonsHeading = "This payslip needs review because:"
    const val correctionDiagnosticHintHeading = "AI flagged this field as possibly mis-extracted:"

    // Upload & Decrypt
    const val uploadHeader = "Import Encrypted Payslip"
    const val uploadDesc = "Secure, 100% offline-first parsing engine"
    const val labelSelectPdf = "Select PDF Payslip"
    const val labelPassword = "Decryption Password"
    const val showPasswordToggle = "Show"
    const val hidePasswordToggle = "Hide"
    const val btnDecrypt = "Decrypt & Parse"
    const val loaderDecrypt = "Decrypting PDF using Secure Enclave..."
    const val uploadDismiss = "Dismiss"
    const val uploadSuccess = "Payslip Imported Successfully!"

    // Dashboard - Officer Info Bar
    const val officerInfoLabel = "Officer"
    const val cdaInfoLabel = "CDA A/C"
    const val panInfoLabel = "PAN"

    // Dashboard - Year/Month Picker
    const val selectYearLabel = "Year"
    const val selectMonthLabel = "Month"
    const val analyzingStatement = "Analyze Payslip"

    // Security Lock Screen
    const val lockScreenTitle = "Secured Portal"
    const val lockScreenSubtitle = "Enter your 4-digit PIN to decrypt your dashboard"
    const val lockScreenError = "Incorrect PIN, please try again"
    const val lockScreenForgotPin = "Forgot PIN?"
    const val lockScreenResetDialogTitle = "Reset Passcode"
    const val lockScreenResetDialogDesc = "Please select a valid statement PDF and enter its decryption password to verify ownership."
    const val lockScreenResetErrorMismatch = "PDF does not match the active user profile."
    const val lockScreenResetConfirmBtn = "Verify & Reset"

    // Settings Interface
    const val settingsAccountSubscriptionHeader = "Account & Subscription"
    const val settingsSecurityPrivacyHeader = "Security & Privacy"
    const val settingsThemeLabel = "App Appearance"
    const val settingsThemeLight = "Light Mode"
    const val settingsThemeDark = "Dark Mode"
    const val settingsThemeSystem = "System Default"
    const val settingsAppLockLabel = "Security Passcode"
    const val settingsAppLockDesc = "Protect your financial data with a local PIN"
    const val settingsProfileHeader = "Salary & Allowance Settings"
    const val settingsProfileDesc = "Manage ranks, allowances, and custom overrides"
    const val settingsProfileName = "Officer Name"
    const val settingsProfileCda = "CDA Account Number"
    const val settingsProfilePan = "PAN Number"
    const val settingsProPlanTitle = "Advanced Tax & Financial Insights"
    const val proTeaserCrownIcon = "👑"
    const val proTeaserAiIcon = "🤖"
    const val proTeaserToolsIcon = "🛠"
    const val aiRegenerateIcon = "🔄"
    const val settingsProPlanDesc = "Unlock personalization & CA-grade tax advice"
    const val settingsProPlanPrice = "₹99 / Year"
    const val settingsProPlanBillingNote = "Yearly Auto-Renewing Subscription"
    const val settingsProPlanActive = "Pro Plan Activated"
    const val settingsDangerZone = "Danger Zone"
    const val settingsDeleteAll = "Reset App & Clear Data"
    const val settingsDeleteConfirm = "Are you sure you want to wipe all local database records? This action is permanent."
    const val settingsDangerZoneDesc = "Wipe all local database statements, cached PDFs, and passcode configuration."
    const val settingsDeleteConfirmTitle = "Wipe App Data?"
    const val settingsDeleteConfirmBtn = "Delete Everything"
    const val btnCancel = "Cancel"
    const val btnBack = "← Back"

    // Passcode Setup Dialog
    const val settingsSetPasscodeTitle = "Set 4-Digit Passcode"
    const val settingsSetPasscodeLabel = "Enter 4-Digit PIN"
    const val settingsSetPasscodeConfirmBtn = "Enable Lock"
    const val settingsProfileSaveBtn = "Save Adjustments"

    // Backup & Restore Card
    const val settingsBackupHeader = "Personal Cloud Sync & Backup"
    const val settingsBackupDesc = "Backup is locally AES-256 encrypted using your password."
    const val settingsBackupLocalBtn = "Local Backup"
    const val settingsRestoreLocalBtn = "Local Restore"
    const val pdfCardTapHint = "Tap to open original statement"
    const val pdfCardBadge = "PDF"
    const val pdfCardOpenCdesc = "Open"
    const val settingsBackupCrossPlatform = "Cross-Platform Portability (iOS ⇄ Android)"
    const val settingsBackupExportBtn = "Export Archive"
    const val settingsBackupImportBtn = "Import Archive"
    const val settingsBackupCancelImportBtn = "Cancel Import"
    const val settingsBackupPasteLabel = "Paste Encrypted Backup String"
    const val settingsBackupDecryptBtn = "Decrypt & Restore"

    // Backup Status Messages
    const val statusSyncSuccess = "Sync Completed!"
    const val statusSyncFailed = "Sync Failed: "
    const val statusRestoreSuccess = "Restore Completed!"
    const val statusRestoreFailed = "Restore Failed: "
    const val statusCopiedSuccess = "Backup String Copied to Clipboard!"
    const val statusExportFailed = "Export Failed: "
    const val statusRestoreComplete = "Restore Complete!"
    const val statusInvalidFormat = "Invalid backup string format"

    // Main Settings Screen
    const val settingsSubtitle = "Manage your profile, security, and data backups"
    const val settingsOfflineFirst = "Offline-First"
    const val settingsOfflineSecureTitle = "100% Offline & Secure"
    const val settingsOfflineSecureDesc = "All payslip decryption and parsing happens locally on your device. Your data never leaves your control."
    const val settingsAiPoweredByProxy = "AI insights powered by Gemini"

    // Sandbox / Testing
    const val settingsStagingTitle = "Staging & Testing Sandbox"
    const val settingsStagingDesc = "Load simulated Army Officer records (2022-2025) to evaluate the analytical tools immediately."
    const val settingsStagingSeedBtn = "Seed Staging Data"
    const val settingsStagingClearBtn = "Clear All"

    // Help & Legal Docs
    const val settingsHelpDocsHeader = "Help & Legal"
    const val settingsHelpFaqTitle = "Frequently Asked Questions (FAQ)"
    const val settingsHelpPrivacyTitle = "Privacy Policy"
    const val settingsHelpAiTitle = "AI Privacy Promise"
    const val settingsHelpDisclaimerTitle = "Legal Disclaimer"

    const val settingsHelpFaqContent = "Q: How is my payslip decrypted?\nA: Decryption happens entirely offline on your device using local AES-256 libraries. Your password is never sent online.\n\nQ: Where is my data stored?\nA: Your data is saved in a secure, local Room database on your device."
    const val settingsHelpPrivacyContent = "We enforce a 100% offline-first architecture. All parsing, decryption, and storage tasks run strictly in your local sandbox. No data leaves your control unless you explicitly run a sync backup."
    const val settingsHelpAiContent = "To preserve confidentiality, the app strips all Personal Identifying Information (PII) like Name, CDA account number, and PAN number from data sent to the Gemini API. Only numeric financial values are processed to generate insights."
    const val settingsHelpDisclaimerContent = "This analytical tool is for reference purposes only. It is not an official app of the PCDA, Ministry of Defence, or the Indian Army. It does not replace professional advice from chartered accountants or official audit statements."

    // Redesign & Pro Tier
    const val settingsProPlanBullet1 = "• CA-Grade Financial Audits & Advice"
    const val settingsProPlanBullet2 = "• Personalized Tax Saving Insights"
    const val settingsProPlanBullet3 = "• Secure Local & Cross-Platform Backups"
    const val settingsProPlanBullet4 = "• 100% Offline & Private Processing"
    const val settingsProUpgradeBtn = "Unlock Pro Tier"
    const val settingsDocumentationHeader = "Help & Legal"
    const val settingsAiInsightsLockedTitle = "CA Level AI Report"
    const val settingsRowThemeLabel = "App Appearance"
    const val settingsRowPasscodeLabel = "App Passcode Lock"
    const val settingsRowBackupLabel = "Secure Backup & Sync"
    const val settingsRowProfileLabel = "Salary & Allowance Settings"
    const val settingsStatusNotConfigured = "Not Configured"
    const val settingsStatusConfigured = "Configured"
    const val settingsStatusProOnly = "Pro Feature"
    const val settingsStatusEnabled = "Enabled"
    const val settingsStatusDisabled = "Disabled"
    const val settingsStatusDefault = "Default"

    // Re-parse All Payslips
    const val settingsRowReparseLabel = "Re-parse All Payslips"
    const val settingsReparseSubtitle = "Fix payslips parsed before an app update"
    const val settingsReparseDialogTitle = "Re-parse All Payslips"
    const val settingsReparseDialogBody = "Re-runs every saved payslip through the current parser and replaces its stored result. Your saved corrections are kept. Enter your payslip PDF password to continue."
    const val settingsReparsePasswordLabel = "Payslip PDF Password"
    const val settingsReparseConfirmBtn = "Re-parse All"
    const val settingsReparseSuccessPrefix = "Re-parsed "
    const val settingsReparseFailedSuffix = "Could not re-parse: "
    const val settingsReparseErrorPrefix = "Re-parse failed: "

    // History Redesign Strings
    const val historyActionDelete = "Delete Statement"
    const val historyConfirmDeleteTitle = "Delete Payslip?"
    const val historyConfirmDeleteMessage = "Are you sure you want to delete this payslip? This action is permanent and cannot be undone."
    const val historyHeaderDescription = "Browse and read your historical military payslip statements"
    const val historyEmptyState = "No payslips in history. Go to Dashboard to import one."
    const val historyActionViewReplica = "View Digital Replica"
    const val historyActionViewOriginal = "View Original PDF"
    const val historyActionShareSummary = "Share Summary"
    const val historyYearlySummary = "Yearly Summary"
    const val historyNetTakeHomeLabel = "Net Take-Home"
    const val historyNetTakeHomeShort = "Take Home"
    const val historyGrossPayLabel = "Gross"
    const val historyDsopLabel = "DSOP"
    const val historyTaxLabel = "Tax"
    const val historyTrendHike = "DA Hike / Increment"
    const val historyTabStatements = "Statements"
    const val historyTabAiReports = "AI Reports"
    const val historyEmptyAiReports = "No saved AI reports. Generate one from the Insights screen."
    const val historyNavigateToInsights = "Go to Insights Screen"
    const val historyPremiumIntelligenceNarrative = "Premium Intelligence Narrative"
    const val historyChevronContentDescription = "Toggle Year Visibility"
    const val historyLedgerTitle = "Historical Ledger Table"
    const val historyLedgerHeaderMonth = "Month"
    const val historyLedgerHeaderBasic = "Basic"
    const val historyLedgerHeaderGross = "Gross"
    const val historyLedgerHeaderNet = "Net"
    const val historyLedgerHeaderDsop = "DSOP"
    const val historyLedgerHeaderTax = "Tax"
    const val dsopSimulatorTitle = "DSOP Compound Simulator"
    const val dsopSimulatorMonthlySub = "Monthly Subscription"
    const val dsopSimulatorTaxWarning = "Tax Warning: Annual DSOP contributions above ₹5 Lakhs (₹41,666/mo) attract income tax on interest earned. Stay below ₹41,666/mo to keep gains 100% tax-free."
    const val dsopSimulatorTaxSafe = "Tax optimized: Annual contribution is below ₹5 Lakhs. All DSOP interest remains 100% tax-free under Section 10(11) of the Income Tax Act."
    const val dsopSimulator5Years = "5 Years"
    const val dsopSimulator10Years = "10 Years"
    const val dsopSimulator15Years = "15 Years"
    const val insightsEmptyState = "Please import or select a payslip to unlock financial insights."
    const val insightsSavingsRateTitle = "Monthly Savings Rate"
    const val insightsSavingsRateTarget = "Target: 20%+. You save "
    const val insightsSavingsRateSuffix = "% of your gross pay in DSOP and AGIF."
    const val executiveSummaryLabel = "Executive Summary"
    const val criticalAlertsLabel = "Critical Alerts"
    const val changesThisMonthLabel = "Changes This Month"
    const val legendNetTakeHome = "Net Take-Home"
    const val legendDsop = "Provident Fund (DSOP)"
    const val legendTax = "Taxes & Cess"
    const val legendOtherDeductions = "Other Deductions"
    const val legendGrossPay = "Gross Pay"
    const val legendNetRemittance = "Net Remittance"
    const val chartNoDataAvailable = "No data available"
    const val pdfIconLabel = "PDF"
    const val pdfTapToOpen = "Tap to open original statement"
    const val dashboardEmptyStateTitle = "No Payslips Imported"
    const val dashboardEmptyStateDesc = "Import your monthly payslips to unlock digital replicas, historical tracking, financial insights, and tax audits."
    const val dashboardEmptyStateLabel = "Tap the + button below to get started"
    const val dashboardEmptyStateDescSandbox = "Import your PDF payslips or seed simulated data from the import screen to view financial analytics."
    const val geminiAiAnalyzeBtn = "Analyze Payslip with Gemini AI"
    const val ledgerMismatchIconDesc = "Ledger mismatch"
    const val ledgerCreditMismatchPrefix = "Credits over by ₹"
    const val ledgerDebitMismatchPrefix = "Debits over by ₹"
    const val correctionDialogSelectAction = "Select Action"
    const val correctionDialogEditOption = "Edit Value"
    const val correctionDialogDeleteOption = "Delete Entry"
    const val correctionDialogAddEarningTitle = "Add Earning Entry"
    const val correctionDialogAddDeductionTitle = "Add Deduction Entry"
    const val correctionDialogCodeHeadLabel = "Code Head (Abbreviation)"
    const val correctionDialogCustomCodeHeadPlaceholder = "e.g., A/o DA, Misc"
    const val correctionDialogAmountLabel = "Amount (₹)"
    const val correctionDialogOriginalAmountLabel = "Original Parsed Amount: ₹"
    const val correctionDialogSaveDraft = "Add to Session"
    const val correctionDialogDeleteWarning = "This entry will be marked as deleted in your local replica session."
    const val correctionSessionActivePrefix = "Draft Session Active"
    const val correctionSessionDiscard = "Discard"
    const val correctionSessionApply = "Apply"
}
