package com.payslipmax.pdfparser.ui.theme

object AppStringsPremium {
    const val geminiAiAnalyzeDesc = "Generate professional tax saving suggestions, investment recommendations, and error audits using Gemini."
    const val geminiAiViewReportBtn = "View Full Audit Report"

    // AI CA Audit card (Phase 5)
    const val aiAuditAnalyzingDesc = "Analyzing your payslip with Gemini AI…"
    const val aiAuditUnlockBtn = "Unlock AI CA Audit"

    // Premium Features Screens Strings
    const val representationTitle = "Claim Generator"
    const val representationSubtitle = "Pay & allowance dispute letters"
    const val representationDraftsEmpty = "No salary discrepancies or missing allowances detected. Representation drafts will appear here if the local audit engine flags any issues."
    const val representationCopyBtn = "Copy"
    const val representationEditBtn = "Edit"
    const val representationSaveBtn = "Save Draft"
    const val representationShareBtn = "Share"
    const val representationExportPdfBtn = "Export PDF"

    // Retirement calculators (RETIREMENT_CALCULATORS gate, Phase 4e). All outputs are estimates.
    const val retCalcTitle = "Retirement Calculators"
    const val retCalcSubtitle = "Pension, gratuity, commutation & leave estimates"
    const val retCalcNoPayslip = "Select a payslip first — these estimates use your current pay figures."
    const val retCalcBasisLabel = "Based on current pay (Basic + MSP + DA)"
    const val retCalcInputsTitle = "Your details"
    const val retCalcQualifyingYearsLabel = "Qualifying service (years)"
    const val retCalcAgeNextBirthdayLabel = "Age next birthday at retirement (20–67)"
    const val retCalcLeaveDaysLabel = "Encashable leave days (max 300)"
    const val retCalcPensionTitle = "Estimated monthly pension"
    const val retCalcPensionNote = "50% of Basic + MSP"
    const val retCalcGratuityTitle = "Estimated retirement gratuity"
    const val retCalcGratuityNote = "¼ × (Basic + MSP + DA) × six-monthly periods (Capped at ₹25L)"
    const val retCalcCommutationTitle = "Commuted lump sum (50%)"
    const val retCalcCommutationResidualPrefix = "Residual monthly pension: "
    const val retCalcCommutationNoFactor = "Enter an age between 20 and 67 to estimate commutation, or verify your factor with PAO."
    const val retCalcLeaveTitle = "Estimated leave encashment"
    const val retCalcLeaveNote = "(Basic + DA) ÷ 30 × days (MSP Excluded per PCDA rules)"
    const val retCalcDisclaimer = "Estimates only, based on your current pay — actual retirement figures depend on last-drawn emoluments and rules in force. Verify with PAO / PCDA(O)."

    // Modern Retirement Planner Components
    const val retHeroTitle = "Retirement Entitlement Summary"
    const val retHeroMonthlyPayoutLabel = "Net Monthly Pension (with DR)"
    const val retHeroDay1CorpusLabel = "Total Day-1 Liquid Corpus"
    const val retDay1CorpusTitle = "Day-1 Lump Sum Payout Breakdown"
    const val retMonthlyPensionTitle = "Monthly Cashflow & Dearness Relief (DR)"
    const val retCommutationSimulatorTitle = "Commutation Decision Simulator"
    const val retCommutationBreakEvenLabel = "Required Reinvestment Yield: "
    const val retDisabilityPensionTitle = "Disability Pension Calculator"
    const val retDisabilityToggleLabel = "Include Medical Board Disability"
    const val retDisabilityPercentLabel = "Disability Percentage (20% - 100%)"
    const val retAgifMaturityTitle = "AGIF Maturity Benefit"
    const val retAgifNote = "Accumulated balance minus ₹1.6L extended cover (100% Tax Free)"
    const val retPmrNoticeTitle = "PMR (Premature Retirement) Mode"
    const val retPmrNoticeDesc = "Officers seeking PMR post-2014 are excluded from 5-year OROP revisions per MoD rules."
    const val retSparshTitle = "SPARSH & PCDA(O) Transition Directory"
    const val retSparshHelpline = "PCDA(O) Pune Helpline: 9309781033 · SPARSH Toll Free: 1800-180-5325"

    const val taxPlanningTitle = "Tax Optimization Planner"
    const val taxPlanningSubtitle = "Form 16 projections & tax-saving suggestions"
    const val taxPlanningGrossYtd = "YTD Gross Salary"
    const val taxPlanningTaxable = "Net Taxable Income"
    const val taxPlanningITax = "Estimated Tax Liability"

    // Modern Tax Planner Strings
    const val taxPlanningFyStatusPrefix = "Financial Year "
    const val taxPlanningMonthsParsedSuffix = " Months Parsed (Projected)"
    const val taxPlanningRegimeBattleTitle = "Old vs. New Tax Regime Comparison"
    const val taxPlanningOldRegimeLabel = "Old Tax Regime"
    const val taxPlanningNewRegimeLabel = "New Tax Regime"
    const val taxPlanningWinnerSavingsBadge = "Saves ₹"
    const val taxPlanningWinnerRegimeRecommended = "Recommended for lowest tax liability"
    const val taxPlanningBreakEvenText = "Min Old Regime Deductions Needed: ₹"
    const val taxPlanningTdsRunwayTitle = "Annual Tax Liability & TDS Runway"
    const val taxPlanningTdsPaidYtd = "TDS Deducted YTD: ₹"
    const val taxPlanningTdsRemaining = "Remaining FY Tax: ₹"
    const val taxPlanningMonthlyTdsRunway = "Projected Monthly TDS: ₹"
    const val taxPlanningTdsSpikeAlertTitle = "⚡ High TDS Spike Warning"
    const val taxPlanningTdsSpikeAlertDesc = "Your monthly tax deduction will jump from ₹"
    const val taxPlanningExemptionsTitle = "Tax Deductions & Sec 10 Exemptions"
    const val taxPlanning80CLabel = "Sec 80C (DSOP + AGIF)"
    const val taxPlanning80CCD1BLabel = "Sec 80CCD(1B) NPS"
    const val taxPlanningHraLabel = "Sec 10(13A) HRA Exemption"
    const val taxPlanningFieldLabel = "Sec 10(14) Field Allowance Exemption"

    const val taxPlanningExemptionsCardTitle = "Defence Exemptions & Deductions"
    const val taxPlanningExemptionsTotalLabel = "Total Old Regime Deductions: ₹"

    const val taxPlanningTipsCardTitle = "💡 Tax Planning Tips & Best Practices"
    const val taxPlanningTip1Title = "Sec 10(14) Field Allowance Exemption"
    const val taxPlanningTip1Desc = "Field Area, High Altitude, and Special Duty allowances are tax-exempt under Section 10(14). Ensure PCDA excludes them from taxable income."
    const val taxPlanningTip2Title = "Automatic Sec 80C via DSOP + AGIF"
    const val taxPlanningTip2Desc = "Your monthly DSOP subscription and AGIF deductions automatically qualify for Sec 80C (up to ₹1.5 Lakhs limit). No extra ELSS is required if already capped."
    const val taxPlanningTip3Title = "New Tax Regime Zero Tax Threshold"
    const val taxPlanningTip3Desc = "Under the New Tax Regime, taxable income up to ₹7 Lakhs (FY 24-25) or ₹12 Lakhs (FY 25-26) has ZERO tax liability after Sec 87A rebate."
    const val taxPlanningTip4Title = "PCDA Declaration Deadline"
    const val taxPlanningTip4Desc = "Submit your tax regime selection to PCDA before December to avoid sudden high TDS deductions in January to March."

    const val taxPlanningNarrativeLedgerTitle = "Month-by-Month Deductions Audit"
    const val taxPlanningNarrativeMonthCol = "Month"
    const val taxPlanningNarrativeTdsCol = "TDS"
    const val taxPlanningNarrativeDsopCol = "DSOP"
    const val taxPlanningNarrativeYtdTotalLabel = "YTD Total:"
    const val taxPlanningNarrativeBenchmarkTitle = "Effective Tax Rate & Peer Benchmark"
    const val taxPlanningNarrativeYourRateLabel = "Your Effective Rate"
    const val taxPlanningNarrativePeerTargetLabel = "Optimal Effective Rate"
    const val taxPlanningNarrativeTdsLabel = "TDS: ₹"
    const val taxPlanningNarrativeDsopLabel = "DSOP: ₹"

    const val taxPlanningConfidenceHigh = "🟢 High Confidence"
    const val taxPlanningConfidenceModerate = "🟡 Moderate Confidence"
    const val taxPlanningConfidencePreliminary = "🔴 Preliminary Estimate"
    const val taxPlanningRuleVersionFooter = "🛡️ Tax Engine: CBDT Rules FY 2025-26 (AY 2026-27) · Version 2026.1 (Verified 01 Jul 2026) · 100% Offline Secured"

    const val retirementTitle = "Retirement Wealth Projection"
    const val retirementSubtitle = "DSOP contribution & compound wealth estimates"
    const val retirementProjectionDisclaimer = "Note: Compounding projections are estimated using a standard interest rate of 7.1% per annum. Actual rates may vary."
    const val premiumToolsTitle = "Premium Financial Tools"
    const val premiumToolsTaxPlanner = "Tax Planner"
    const val premiumToolsDsopSimulator = "DSOP Simulator"

    const val representationMonthLabel = "Month:"
    const val representationRecipientPcda = "Recipient: PCDA Pune"
    const val representationEditDraftTitle = "Edit Draft:"

    const val retirementNoBalance = "Import a payslip with DSOP ledger balance to simulate growth."
    const val taxPlanningSavingsProjections = "Section 80C & 80D Tax Savings Projections"
    const val taxPlanningNoProjections = "No YTD Tax Projections available for this month."

    // PRO Features Catalog (Phase 3) — benefit-only copy, no prices (D8)
    const val proCatalogTitle = "PRO Features"
    const val proCatalogSubtitle = "Everything included with PayslipMax Pro"
    const val proCatalogIncludedLabel = "Included"
    const val proCatalogComingSoonLabel = "Coming soon"
    const val proCatalogSettingsEntrySubtitle = "See everything Pro unlocks"

    const val proCatalogPremiumIntelligenceTitle = "Premium Intelligence"
    const val proCatalogPremiumIntelligenceDesc = "Full recovery opportunities, tax savings and CA-level audit in one view"
    const val proCatalogPremiumIntelligenceIcon = "👑"
    const val proCatalogWealthTitle = "Wealth Optimization"
    const val proCatalogWealthDesc = "80C/NPS headroom and DSOP corpus growth projections"
    const val proCatalogWealthIcon = "💰"
    const val proCatalogAiAuditTitle = "AI CA Audit"
    const val proCatalogAiAuditDesc = "On-device AI reviews your payslip for PCDA errors and savings"
    const val proCatalogAiAuditIcon = "🤖"
    const val proCatalogAnomalyTitle = "Advanced Anomaly Detection"
    const val proCatalogAnomalyDesc = "DSOP compliance, arrears, entitlement and recovery-risk audits"
    const val proCatalogAnomalyIcon = "🔍"
    const val proCatalogClaimTitle = "Claim Generator"
    const val proCatalogClaimDesc = "Generate official PCDA(O) representation PDFs"
    const val proCatalogBackupTitle = "Encrypted Backup"
    const val proCatalogBackupDesc = "Create AES-256 encrypted backups of your payslip data"
    const val proCatalogBackupIcon = "🔐"
    const val proCatalogRetCalcTitle = "Retirement Calculators"
    const val proCatalogRetCalcDesc = "Estimate pension, gratuity, commutation & leave encashment"
    const val proCatalogRetCalcIcon = "🧮"

    const val taxPlanningPreliminaryEstimatePrefix = "Preliminary estimate · "
    const val taxPlanningOfMonthsSuffix = " of 12"
    const val taxPlanningBestAchievableRateLabel = "Best Achievable Rate"

    const val retCommutationSubtitle = "Compare Lump Sum Advance vs. Monthly Pension. Commuted portion is restored after 15 years."
    const val retCommutationLumpSumLabel = "Lump Sum"
    const val retCommutationMonthlyNetLabel = "Monthly Net"
    const val retCommutationReqRoiLabel = "Req ROI"
    const val retSparshDgrTitle = "🎓 Directorate General Resettlement (DGR) & AWPO Transition"
    const val retSparshDgrDescription = "Officers can register for DGR courses (IIM/XLRI Executive Management) in their last year of service. AWPO registration facilitates corporate placement (Corporate Security, Supply Chain, Admin)."
}
