package com.payslipmax.pdfparser.ui.theme

object AppStringsPremium {
    // Premium Features Screens Strings
    const val representationTitle = "Claim Generator"
    const val representationSubtitle = "Pay & allowance dispute letters"
    const val representationDraftsEmpty = "No salary discrepancies or missing allowances detected. Representation drafts will appear here if the local audit engine flags any issues."
    const val representationCopyBtn = "Copy"
    const val representationEditBtn = "Edit"
    const val representationSaveBtn = "Save Draft"
    const val representationShareBtn = "Share"
    const val representationExportPdfBtn = "Export PDF"

    // Retirement calculators (RETIREMENT_CALCULATORS gate, Phase 4e). All outputs are estimates.
    const val retCalcTitle = "Retirement Calculators"
    const val retCalcSubtitle = "Pension, gratuity, commutation & leave estimates"
    const val retCalcNoPayslip = "Select a payslip first — these estimates use your current pay figures."
    const val retCalcBasisLabel = "Based on current pay (Basic + MSP + DA)"
    const val retCalcInputsTitle = "Your details"
    const val retCalcQualifyingYearsLabel = "Qualifying service (years)"
    const val retCalcQualifyingYearsHint = "Determines Gratuity. Min 20 yrs needed for pension."
    const val retCalcAgeNextBirthdayLabel = "Age next birthday at retirement (20–67)"
    const val retCalcAgeHint = "Sets Commutation factor. Younger age = higher lump sum."
    const val retCalcLeaveDaysLabel = "Encashable leave days (max 300)"
    const val retCalcLeaveHint = "(Basic + DA) ÷ 30 × days. MSP excluded per PCDA."
    const val retCalcDsopHint = "100% Tax-Free provident fund balance in Day-1 corpus."
    const val retCalcPensionTitle = "Estimated monthly pension"
    const val retCalcPensionNote = "50% of Basic + MSP"
    const val retCalcGratuityTitle = "Estimated retirement gratuity"
    const val retCalcGratuityNote = "¼ × (Basic + MSP + DA) × six-monthly periods (Capped at ₹25L)"
    const val retCalcCommutationTitle = "Commuted lump sum (50%)"
    const val retCalcCommutationResidualPrefix = "Residual monthly pension: "
    const val retCalcCommutationNoFactor = "Enter an age between 20 and 67 to estimate commutation, or verify your factor with PAO."
    const val retCalcLeaveTitle = "Estimated leave encashment"
    const val retCalcLeaveNote = "(Basic + DA) ÷ 30 × days (MSP Excluded per PCDA rules)"
    const val retCalcDisclaimer = "Estimates only, based on your current pay — actual retirement figures depend on last-drawn emoluments and rules in force. Verify with PAO / PCDA(O)."

    // Modern Retirement Planner Components
    const val retHeroTitle = "Retirement Entitlement Summary"
    const val retHeroMonthlyPayoutLabel = "Net Monthly Pension (with DR)"
    const val retHeroDay1CorpusLabel = "Total Day-1 Liquid Corpus"
    const val retDay1CorpusTitle = "Day-1 Lump Sum Payout Breakdown"

    // CA Tax Audit & Commutation Advisory Strings
    const val retCaTaxAuditTitle = "CA Tax Audit & Income Tax Exemptions"
    const val retCaTaxAuditSubtitle = "Defence pension tax classification under Income Tax Act"
    const val retCaTaxFreeCorpusLabel = "Day-1 Tax-Free Corpus (Sec 10)"
    const val retCaTaxableMonthlyLabel = "Taxable Monthly Flow (Sec 17 Salaries)"
    const val retCaTaxExemptNotes = "100% Tax-Exempt u/s 10: DSOP, Gratuity, Commutation & Leave Encashment"
    const val retCaVerdictTitle = "CA Commutation Reinvestment Verdict"
    const val retCaVerdictRecommend = "Recommendation: Commute 50% if you can reinvest the lump sum above "
    const val retCaVerdictRoiSuffix = "% p.a. post-tax."
    const val retCaRestorationNotice = "PCDA automatically restores full monthly pension after 15 years (180 payments)."
    const val retMonthlyPensionTitle = "Monthly Cashflow & Dearness Relief (DR)"
    const val retCommutationSimulatorTitle = "Commutation Decision Simulator"
    const val retCommutationBreakEvenLabel = "Required Reinvestment Yield: "
    const val retDisabilityPensionTitle = "Disability Pension Calculator"
    const val retDisabilityToggleLabel = "Include Medical Board Disability"
    const val retDisabilityPercentLabel = "Disability Percentage (20% - 100%)"
    const val retAgifMaturityTitle = "AGIF Maturity Benefit"
    const val retAgifNote = "Accumulated balance minus ₹1.6L extended cover (100% Tax Free)"
    const val retPmrNoticeTitle = "PMR (Premature Retirement) Mode"
    const val retPmrNoticeDesc = "Officers seeking PMR post-2014 are excluded from 5-year OROP revisions per MoD rules."
    const val retSparshTitle = "SPARSH & PCDA(O) Transition Directory"
    const val retSparshHelpline = "PCDA(O) Pune Helpline: 9309781033 · SPARSH Toll Free: 1800-180-5325"

    const val taxPlanningTitle = "Tax Planner"
    const val taxPlanningSubtitle = "Form 16 projections & tax-saving suggestions"
    const val taxPlanningGrossYtd = "YTD Gross Salary"
    const val taxPlanningTaxable = "Net Taxable Income"
    const val taxPlanningITax = "Estimated Tax Liability"

    // Modern Tax Planner Strings
    const val taxPlanningFyStatusPrefix = "Financial Year "
    const val taxPlanningRegimeBattleTitle = "Old vs. New Tax Regime Comparison"
    const val taxPlanningOldRegimeLabel = "Old Tax Regime"
    const val taxPlanningNewRegimeLabel = "New Tax Regime"
    const val taxPlanningWinnerSavingsBadge = "Saves ₹"
    const val taxPlanningWinnerRegimeRecommended = "Recommended for lowest tax liability"
    const val taxPlanningBreakEvenText = "Min Old Regime Deductions Needed: ₹"
    const val taxPlanningCurrentDeductionsText = "Your Current Old Regime Deductions: ₹"
    const val taxPlanningDeductionGapText = "Gap To Switch-Worthy: ₹"
    const val taxPlanningTdsRunwayTitle = "Annual Tax Liability & TDS Runway"
    const val taxPlanningTdsPaidYtd = "TDS Deducted YTD: ₹"
    const val taxPlanningTdsRemaining = "Remaining FY Tax: ₹"
    const val taxPlanningMonthlyTdsRunway = "Projected Monthly TDS: ₹"
    const val taxPlanningTdsSpikeAlertTitle = "⚡ High TDS Spike Warning"
    const val taxPlanningTdsSpikeAlertDesc = "Your monthly tax deduction will jump from ₹"
    const val taxPlanningExemptionsTitle = "Tax Deductions & Sec 10 Exemptions"
    const val taxPlanning80CLabel = "Sec 80C (DSOP + AGIF)"
    const val taxPlanning80CCD1BLabel = "Sec 80CCD(1B) NPS"
    const val taxPlanningHraLabel = "Sec 10(13A) HRA Exemption"
    const val taxPlanningFieldLabel = "Sec 10(14) Field Allowance Exemption"

    const val taxPlanningExemptionsCardTitle = "Defence Exemptions & Deductions"
    const val taxPlanningExemptionsTotalLabel = "Total Old Regime Deductions: ₹"
    const val taxPlanningExemptionsUnavailableNewRegimeNote =
        "Not available under your active New Tax Regime (Section 115BAC) — shown as ₹0, not omitted"
    const val taxPlanningFieldCapConservativeAssumptionNote =
        "Field allowance cap assumed conservatively — the specific Rule 2BB category couldn't be identified from this payslip"

    // D13: tips 1 and 2 are regime-conditional (Sec 10(14) field caps and Sec 80C both stop applying
    // under the New Regime) -- TaxEducativeTipsCard picks the Old/New variant by active regime rather
    // than showing one regime's rules to every user.
    const val taxPlanningTipsCardTitle = "💡 Tax Planning Tips & Best Practices"
    const val taxPlanningTip1Title = "Sec 10(14) Field Allowance Exemption"
    const val taxPlanningTip1DescOld = "Field Area, High Altitude, and Special Duty allowances are exempt under Section 10(14), Rule 2BB — capped per notified category (e.g. up to ₹50,400/yr for Highly Active Field Area), not the full amount received."
    const val taxPlanningTip1DescNew = "Section 10(14) field and special-duty allowance exemptions are not available under the New Tax Regime — these allowances are fully taxable while you remain on New Regime."
    const val taxPlanningTip2Title = "Sec 80C via DSOP + AGIF"
    const val taxPlanningTip2DescOld = "Your monthly DSOP subscription and AGIF deductions count toward Sec 80C, up to the ₹1.5 Lakh annual limit — not automatic beyond that cap; any headroom needs additional 80C investment."
    const val taxPlanningTip2DescNew = "Section 80C does not exist under the New Tax Regime — your DSOP and AGIF contributions currently earn ₹0 tax benefit from them."
    const val taxPlanningTip3Title = "New Tax Regime Zero Tax Threshold"
    const val taxPlanningTip3Desc = "Under the New Tax Regime, taxable income up to ₹7 Lakhs (FY 24-25) or ₹12 Lakhs (FY 25-26) has ZERO tax liability after Sec 87A rebate."
    const val taxPlanningTip4Title = "Regime Intimation Timing"
    const val taxPlanningTip4Desc = "The PCDA(O) regime-switch utility is available year-round, not only before December — intimating early avoids a bunched, higher TDS in the Jan–Mar quarter of the FY."

    const val taxPlanningNarrativeLedgerTitle = "Month-by-Month Deductions Audit"
    const val taxPlanningNarrativeMonthCol = "Month"
    const val taxPlanningNarrativeTdsCol = "TDS"
    const val taxPlanningNarrativeDsopCol = "DSOP"
    const val taxPlanningNarrativeYtdTotalLabel = "YTD Total:"
    const val taxPlanningNarrativeTdsLabel = "TDS: ₹"
    const val taxPlanningNarrativeDsopLabel = "DSOP: ₹"

    const val taxPlanningConfidenceHigh = "🟢 High Confidence"
    const val taxPlanningConfidenceModerate = "🟡 Moderate Confidence"
    const val taxPlanningConfidencePreliminary = "🔴 Preliminary Estimate"
    const val taxPlanningRuleVersionFooter = "🛡️ Tax Engine: CBDT Rules FY 2025-26 (AY 2026-27) · Version 2026.1 (Verified 01 Jul 2026) · 100% Offline Secured"

    const val retirementTitle = "DSOP Simulator"
    const val retirementSubtitle = "DSOP contribution & compound wealth estimates"
    const val retirementProjectionDisclaimer = "Note: Compounding projections are estimated using a standard interest rate of 7.1% per annum. Actual rates may vary."
    const val premiumToolsTitle = "Premium Financial Tools"
    const val premiumToolsTaxPlanner = "Tax Planner"
    const val premiumToolsDsopSimulator = "DSOP Simulator"

    const val representationMonthLabel = "Month:"
    const val representationRecipientPcda = "Recipient: PCDA Pune"
    const val representationEditDraftTitle = "Edit Draft:"

    const val retirementNoBalance = "Import a payslip with DSOP ledger balance to simulate growth."
    const val taxPlanningSavingsProjections = "Section 80C & 80D Tax Savings Projections"
    const val taxPlanningNoProjections = "No YTD Tax Projections available for this month."

    // Premium Features Catalog (Phase 3) — benefit-only copy, no prices (D8)
    const val premiumCatalogTitle = "Premium Features"
    const val premiumCatalogSubtitle = "Everything included with PayslipMax Premium"
    const val premiumCatalogIncludedLabel = "Included"
    const val premiumCatalogComingSoonLabel = "Coming soon"
    const val premiumCatalogSettingsEntrySubtitle = "See everything Premium unlocks"

    const val premiumCatalogPremiumIntelligenceTitle = "Premium Intelligence"
    const val premiumCatalogPremiumIntelligenceDesc = "Full recovery opportunities, tax savings and CA-level audit in one view"
    const val premiumCatalogPremiumIntelligenceIcon = "👑"
    const val premiumCatalogWealthTitle = "Wealth Optimization"
    const val premiumCatalogWealthDesc = "80C/NPS headroom and DSOP corpus growth projections"
    const val premiumCatalogWealthIcon = "💰"
    const val premiumCatalogAnomalyTitle = "Advanced Anomaly Detection"
    const val premiumCatalogAnomalyDesc = "DSOP compliance, arrears, entitlement and recovery-risk audits"
    const val premiumCatalogAnomalyIcon = "🔍"
    const val premiumCatalogClaimTitle = "Claim Generator"
    const val premiumCatalogClaimDesc = "Generate official PCDA(O) representation PDFs"
    const val premiumCatalogBackupTitle = "Encrypted Backup"
    const val premiumCatalogBackupDesc = "Create AES-256 encrypted backups of your payslip data"
    const val premiumCatalogBackupIcon = "🔐"
    const val premiumCatalogRetCalcTitle = "Retirement Calculators"
    const val premiumCatalogRetCalcDesc = "Estimate pension, gratuity, commutation & leave encashment"
    const val premiumCatalogRetCalcIcon = "🧮"

    const val taxPlanningPreliminaryEstimatePrefix = "Preliminary estimate · "
    const val taxPlanningOfMonthsSuffix = " of 12"

    const val retCommutationSubtitle = "Compare Lump Sum Advance vs. Monthly Pension. Commuted portion is restored after 15 years."
    const val retCommutationLumpSumLabel = "Lump Sum"
    const val retCommutationMonthlyNetLabel = "Monthly Net"
    const val retCommutationReqRoiLabel = "Req ROI"
    const val retSparshDgrTitle = "🎓 Directorate General Resettlement (DGR) & AWPO Transition"
    const val retSparshDgrDescription = "Officers can register for DGR courses (IIM/XLRI Executive Management) in their last year of service. AWPO registration facilitates corporate placement (Corporate Security, Supply Chain, Admin)."
}
