package com.payslipmax.pdfparser.ui.theme

object TransparencyStrings {
    const val transparencyTitle = "Data Privacy & Transparency Audit"
    const val transparencyMessage = "Below is the exact data payload prepared for server transmission. All personal identity markers (Name, PAN, Service Number, CDA Account) have been completely redacted locally on your device."
    const val transparencyLabelRaw = "Raw Local Data"
    const val transparencyLabelSanitized = "Scrubbed ToSend Data"
    const val transparencyDisclaimer = "I verify that no private identity markers are leaving my device."
    const val transparencyActionApprove = "Approve & Analyze"
    const val labelOfficerName = "Name: "
    const val labelCdaAccount = "CDA A/C: "
    const val labelPanNumber = "PAN: "
    const val labelFilename = "File: "
    const val labelPerson = "Person: "
    const val labelAnonymous = "anonymous"
    const val labelBasicPay = "Basic Pay: "
    const val labelDA = "DA: "
    const val labelMSP = "MSP: "
    const val labelTPTA = "TPTA: "
    const val labelHRA = "HRA: "
    const val labelCredits = "Credits/Gross: "
    const val labelDSOP = "DSOP: "
    const val labelITax = "ITAX: "
    const val labelAGIF = "AGIF: "
    const val labelDebits = "Debits: "
    const val labelNetRemittance = "Net Remittance: "
    const val labelDsopBalance = "DSOP Balance: "
    const val labelRationMoney = "Ration Money: "
    const val labelSpecialForces = "Special Forces: "
    const val labelFieldAllce = "Field Allce: "
    const val labelRiskHardship = "Risk/Hardship: "
    const val labelCEA = "CEA: "
    const val labelNPA = "NPA: "
    const val labelMedicalAllce = "Medical Allce: "
    const val labelMiscEarn = "Misc Earn: "
    const val labelEduCess = "Edu Cess: "
    const val labelLicenceFee = "Licence Fee: "
    const val labelFurnitureRent = "Furniture Rent: "
    const val labelWaterCharges = "Water Charges: "
    const val labelElectricity = "Electricity: "
    const val labelBarrackDamage = "Barrack Damage: "
    const val labelAOBF = "AOBF: "
    const val labelAgifLoanRec = "AGIF Loan Rec: "
    const val labelMiscDeduct = "Misc Deduct: "
}
