package com.payslipmax.pdfparser.guide.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The Claim Guide bundle, generated by `docs/Plan/rule_cards/tools/bundle.py` from the authored rule cards.
 * Plain strings and lists only (no polymorphic or sealed serialized types) so the release build needs just
 * the narrow keep rule in `proguard-rules.pro`. Area, case and facet ids stay strings, so a new area or
 * chapter is a data-only change.
 */
@Serializable
data class GuideBundle(
    val version: Int,
    val generated: String = "",
    @SerialName("rates_as_of") val ratesAsOf: String,
    val limits: GuideLimits,
    val nav: List<GuideArea>,
    /** Facet key (for example "Q") to its label (for example "Who qualifies"). Content, not UI copy. */
    val facets: Map<String, String>,
    val cards: List<GuideCard>,
    /** The rupee figures behind the "your figure" line (phase E6); null in a bundle that carries none. */
    val figures: GuideFigures? = null,
)

/** Word and bullet limits the compiler enforced; the validator rechecks them on every load. */
@Serializable
data class GuideLimits(
    val title: Int,
    val answer: Int,
    val bullets: Int,
    @SerialName("bullet_words") val bulletWords: Int,
    val visible: Int,
    val details: Int,
)

@Serializable
data class GuideArea(
    val id: String,
    val title: String,
    val cases: List<GuideCase>,
)

/** A case tile. [cards] are the cards homed here, in display order; [also] are cards homed elsewhere. */
@Serializable
data class GuideCase(
    val id: String,
    val title: String,
    val sub: String = "",
    val cards: List<String>,
    val also: List<String> = emptyList(),
)

@Serializable
data class GuideCard(
    val id: String,
    val domain: String,
    val topic: String = "",
    val title: String,
    val answer: String,
    val key: List<String>,
    val attach: List<String> = emptyList(),
    val watch: List<String> = emptyList(),
    val cite: String = "",
    val details: String = "",
    val chips: List<String> = emptyList(),
    /** Placeholder spec (for example "level:food_rate"); the only cards allowed a raw `{` in their text. */
    val personal: String = "",
    val status: String = "",
    val facet: String,
    /** Id of the one case this card is homed in. */
    val nav: String,
    /** True when the card carries an open review point: shown as the "Unverified point" chip. */
    val unverified: Boolean = false,
) {
    /** Typed chips; a chip this app version does not know maps to [GuideChip.UNKNOWN], which the UI ignores. */
    val trustChips: List<GuideChip> get() = chips.map(GuideChip::fromKey)

    /** The "No official source" chip. Owner rule (2026-10-07): exactly the cards with no cite. */
    val hasNoOfficialSource: Boolean get() = cite.isBlank()
}

enum class GuideChip {
    RATES,
    AMENDED,
    GUIDANCE,
    UNKNOWN,
    ;

    companion object {
        fun fromKey(key: String): GuideChip = entries.firstOrNull { it != UNKNOWN && it.name == key } ?: UNKNOWN
    }
}

/**
 * The owner-approved rates behind the "your figure" line, generated from `docs/Plan/rule_cards/figures.json`. No rupee
 * figure is written in Kotlin: the resolver reads these. Every field has a default or is optional so a newer bundle
 * that adds modes or fields still loads; a mode this version does not know simply shows no line.
 */
@Serializable
data class GuideFigures(
    @SerialName("da_step") val daStep: GuideDaStep,
    /** Figure key (for example "food_rate") to its data. */
    val figures: Map<String, GuideFigure>,
)

/** A rate rises by [increasePercent] each time DA rises by [perDaPercent] (MoD 15-09-2017: 25% per 50%). */
@Serializable
data class GuideDaStep(
    @SerialName("per_da_percent") val perDaPercent: Int,
    @SerialName("increase_percent") val increasePercent: Int,
)

/**
 * One personal figure. [mode] is `da_step` (band base raised by the DA step), `percent_of_basic`, `plus_da` (band base
 * plus DA on it) or `rate_table` (a percent of basic by city class and DA step). [assumption] is content, like card text.
 */
@Serializable
data class GuideFigure(
    val card: String,
    val mode: String,
    val assumption: String = "",
    @SerialName("effective_from") val effectiveFrom: String = "",
    val percent: Int = 0,
    val bands: List<GuideFigureBand> = emptyList(),
    val classes: Map<String, List<GuideRateStep>> = emptyMap(),
)

/** Pay levels (labels as printed, for example "12A") sharing one [base]; [cityClass] is `HIGHER`, `OTHER` or `ANY`. */
@Serializable
data class GuideFigureBand(
    val levels: List<String>,
    @SerialName("city_class") val cityClass: String = "ANY",
    val base: Int,
)

/** From [fromDaPercent] upwards a city class gets [percent] of basic pay, in force from [effectiveFrom]. */
@Serializable
data class GuideRateStep(
    @SerialName("from_da_percent") val fromDaPercent: Int,
    val percent: Int,
    @SerialName("effective_from") val effectiveFrom: String,
)
