package com.payslipmax.pdfparser.guide.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The Claim Guide bundle, generated by `docs/Plan/rule_cards/tools/bundle.py` from the authored rule cards.
 * Plain strings and lists only (no polymorphic or sealed serialized types) so the release build needs just
 * the narrow keep rule in `proguard-rules.pro`. Area, case and facet ids stay strings, so a new area or
 * chapter is a data-only change.
 */
@Serializable
data class GuideBundle(
    val version: Int,
    val generated: String = "",
    @SerialName("rates_as_of") val ratesAsOf: String,
    val limits: GuideLimits,
    val nav: List<GuideArea>,
    /** Facet key (for example "Q") to its label (for example "Who qualifies"). Content, not UI copy. */
    val facets: Map<String, String>,
    val cards: List<GuideCard>,
)

/** Word and bullet limits the compiler enforced; the validator rechecks them on every load. */
@Serializable
data class GuideLimits(
    val title: Int,
    val answer: Int,
    val bullets: Int,
    @SerialName("bullet_words") val bulletWords: Int,
    val visible: Int,
    val details: Int,
)

@Serializable
data class GuideArea(
    val id: String,
    val title: String,
    val cases: List<GuideCase>,
)

/** A case tile. [cards] are the cards homed here, in display order; [also] are cards homed elsewhere. */
@Serializable
data class GuideCase(
    val id: String,
    val title: String,
    val sub: String = "",
    val cards: List<String>,
    val also: List<String> = emptyList(),
)

@Serializable
data class GuideCard(
    val id: String,
    val domain: String,
    val topic: String = "",
    val title: String,
    val answer: String,
    val key: List<String>,
    val attach: List<String> = emptyList(),
    val watch: List<String> = emptyList(),
    val cite: String = "",
    val details: String = "",
    val chips: List<String> = emptyList(),
    /** Placeholder spec (for example "level:food_rate"); the only cards allowed a raw `{` in their text. */
    val personal: String = "",
    val status: String = "",
    val facet: String,
    /** Id of the one case this card is homed in. */
    val nav: String,
    /** True when the card carries an open review point: shown as the "Unverified point" chip. */
    val unverified: Boolean = false,
) {
    /** Typed chips; a chip this app version does not know maps to [GuideChip.UNKNOWN], which the UI ignores. */
    val trustChips: List<GuideChip> get() = chips.map(GuideChip::fromKey)

    /** The "No official source" chip. Owner rule (2026-10-07): exactly the cards with no cite. */
    val hasNoOfficialSource: Boolean get() = cite.isBlank()
}

enum class GuideChip {
    RATES,
    AMENDED,
    GUIDANCE,
    UNKNOWN,
    ;

    companion object {
        fun fromKey(key: String): GuideChip = entries.firstOrNull { it != UNKNOWN && it.name == key } ?: UNKNOWN
    }
}
